version: "3"

services:
  api:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:s3cr3t@db:5432/inventory_db
    ports:
      - "8000:8000"

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=inventory_db

volumes:
  postgres_data:
